language: php

php:
  - '7.1'
env:
  global:
    - ZIP_FILENAME=bmlt-tabbed-map-build${TRAVIS_BUILD_NUMBER}-${TRAVIS_COMMIT}.zip
    - S3_BUCKET=archives.bmlt.app
    - S3_KEY=bmlt-tabbed-map
jobs:
  include:

    - stage: lint
      install:
        - composer install
      script:
        - find . -name "*.php" ! -path '*/vendor/*' -print0 | xargs -0 -n1 -P8 php -l
        - vendor/squizlabs/php_codesniffer/bin/phpcs --warning-severity=6 --standard=PSR2 --ignore=vendor --extensions=php --report=summary ./
    - stage: zip file
      env:
        - BUILD_DIR=build
        - DIST_DIR_S3=dist/s3
        - DIST_DIR_GITHUB=dist/github
        - GITHUB_RELEASE_FILENAME=bmlt-tabbed-map.zip
        - PLUGIN="bmlt-tabbed-map"
        - MAINFILE="bmlt_tabbed_map.php"
      script:
        - find ./ -type d | xargs chmod 755
        - find ./ -name '*.php' | xargs chmod 644
        - zip -r $ZIP_FILENAME ./ -x "*.git*" -x "*.editorconfig*" -x "*.travis.yml*" -x "*vendor*" -x "composer.*" && mkdir $BUILD_DIR && mv $ZIP_FILENAME $BUILD_DIR/
      before_deploy:
        - mkdir -p $DIST_DIR_S3 && cp $BUILD_DIR/$ZIP_FILENAME $DIST_DIR_S3/$ZIP_FILENAME
        - mkdir -p $DIST_DIR_GITHUB && cp $BUILD_DIR/$ZIP_FILENAME $DIST_DIR_GITHUB/$GITHUB_RELEASE_FILENAME
      deploy:
        - provider: s3
          access_key_id: AKIAI7JHYFA6DI3WYP5A
          secret_access_key:
            secure: r7mXmA3eqzcwoz1sMHLgC4YZ5Kyg+f+W16UHq5Z4FSjBbgjXUFvu8QM3ATIX3oomGQl7m3GYlzoiEdx3wsZVkqZrgd9gDZ3m3Fvp46oPvQZXWtkOzKocWGu7g5Mu7SBc4xSr+fJJ1SMYNxi1OjYUC3NETx/lwiW+s4RzP94+UyN6nGu8W5j5AGWkh1sdXBDCiHBHi1v5j9pJORoIpaca0Ubm3DZvZZbsf7sdpNpH27FOp3RpTwqHlHqfWM6vcOuRDC/LJ9xaVp/bh8bhGAV1RrdiZh18TWto1ZL4QmyZYHABO01Q2ZKUdRlpvrHwvRv4b0H9BwrZMzcml+ifilQbtzpP6vSnTF9p5OMGQUSiA96B9ZIvQx6wky7bHOy+PhHC3atqwBSb5kIEmx9ROCnmk+IDDH6pz6I3kPif4w414JflLP4EaHMc4crvurkB7rNUaTTYQHmbK8CBrDMpJ6JYJJA3be8nZLE55Lg8RT5QiUS877aTqRp/7SiXgZHoHH7xjs3+yN4or7u3KzyZjjj+Bn4mnfz9xL3U0o+ZCVkld062K9HEtllpAqwEGhTm3Gb3tVqVlvBqbi/nmP1GuJfDgnjqQlbNjDQFKoos4DLt71dYgbr+yvcKhwBeZgnI8SkPw9oHv7sHDJDHOS8PA23+MzXX5XvgFa4ShcgSSF7JGHI=
          bucket: "$S3_BUCKET"
          local_dir: "$DIST_DIR_S3"
          upload-dir: "$S3_KEY"
          skip_cleanup: true
          on:
            all_branches: true
        - provider: releases
          api_key:
            secure: a6JrIVAvDW5Fg+75Cmq9PrI5bFnzgYi51N7B54MLg4pUO3X8Q0bpfLZ6JTNqh9+Lee5pzco/cc4SdnwzGHowkwrFvYf2k/7AQiM3lNE4Qekg8JTf7SfojL90CHplLTxXD9hBkh9QKim2T7FxEvRt7TKtg3/7re53yJUTKOvckxsyBGuAD3Q7AvIWV/OaO08pVhzR/Pa1JsICvIzGUCi3UyeZn3hqRIOOvvamhg8jCfIaYU5tI5VApSJ/eBwA2tRTKRTOw4sYC3rNaUO7RMRuoBKxiU6U0JFQDgNFvKwdpiDL2BSXAAxxiYiA84rrTFyPuKOMRaT/ZI3HUTpQ2IBxD7u7oTOxnaozmltd+I57M/0EJBIOq+Ay+WJoLR/1ZLH1Pc6PJWVJegqdHVI+4TdGzlRORChSQgUXXNbVWT1JoScMuSNm55WSGpqG6AI2F5pihU8iDaAF3T98G7Z5V3Fx7cRmt3SvqNeqCW2VewGzeCxUZYcbkTMX3BcEHzrUkZMQ2+Ofvc7BbtoE+sIQZH2M8bCvsE9DENroq32JXkGSGMubp4qEDYsgfnMblJ/Qj52ZKEwJAwNq/BnO8Sss6ZpG4pUdXl6ZIQuw7mo66WLkTvTg0nDVk04/QjvifSe3WUQF9RqirmnekBFlFmdcivPruuoNPhHJXcM3VsZ8vMub51A=
          file: "$DIST_DIR_GITHUB/$GITHUB_RELEASE_FILENAME"
          skip_cleanup: true
          name: "$TRAVIS_TAG"
          on:
            tags: true
notifications:
  slack:
    rooms:
      - secure: bmoIugz9sorNakDw7LnfC3iB7a4CnhuZeZBAVxefSoqipbZAGLoA86pSaDwSK3kNsCRAUXyHJ0pBxxJuCO5jrQKhl9TNBFQQ60KPvn3LQj9OXXTSHp4qoqBytipQGyjeqySu4fJt8Lc0u8FQ0qinxn21qF7K7c54aygVKQd+nxf/+9rVzSOJIY+c6UEBb9FwKfHl9cOJy8nTHYPNl0ZbQaYVS1gvyOV2jzrlurOXb0t2xYs2W9EOAjUd2E4ZVaD8EEyRZ9zcvy8ne41qZGBLMJjHZo6TdN4x0AdEYiITst5fKj+YILNCaVQMyURu5h65RPVXyjZ/eIOUixSt1EOpMTxWcRiDn3H7B2F7eEUIXyo/c5x1AEWEQFLGK+/PEqWx/zaBG0rJJdzVbLaqet2kg5piy+f84EBCZiXm7CZIYPMSjLJo9AJDcY9iSRgvpRnkSagHZAgMILNut53aNPd8i3FoOeycPwux/KDQpSz0uIpn4xu26VY0bzxJ8N27VugUhmNhLCN05Hgw8GoDjEoh4EgPPsdNVzXT4mzpjx2GfhRZOm/78LUSDB/w3oIAEPzRFfhberBAo0l2w9T5+Ynbw9yyquYgNUOW/nMhbwqOPbWqndHa8Xume0DXp2COHEqoSZx4gDIIRRKjKdsrFjjasWB5K7IQXQfBoiGAL7EscNA=
    on_success: change
  email: false
