version: "3.9"
    
services:
  db:
    image: mariadb:10.11
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: somewordpress
      MARIADB_DATABASE: wordpress
      MARIADB_USER: wordpress
      MARIADB_PASSWORD: wordpress
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - wordpress_data:/var/www/html
      - ../bmlt_tabbed_map/:/var/www/html/wp-content/plugins/bmlt_tabbed_map:ro
      - ./logs/:/var/log/apache2
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DEBUG: true
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
volumes:
  db_data: {}
  wordpress_data: {}